# Example: Using one AI reviewer with a custom prompt
#
# Triggers:
# - Automatically on PR open/ready_for_review
# - On-demand via /claude comment (requires write access)
#
# Custom prompts:
# - The 'prompt' input overrides .github/prompts/ai-review.md if both exist

name: Claude Code Review

on:
  pull_request:
    types: [opened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  claude-review:
    uses: lambdaclass/actions/.github/workflows/ai-review-claude.yml@v1
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    with:
      model: 'sonnet'
      prompt: |
        Review this pull request focusing on:

        1. **Security** - SQL injection, XSS, auth issues, input validation
        2. **Bugs** - Logic errors, null checks, edge cases
        3. **Performance** - N+1 queries, unnecessary allocations

        Be concise. Only flag real issues.
